const nav=document.querySelector('.site-header');
const menu=document.querySelector('.menu-toggle');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.desktop-nav a,.header-book').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('menu-open');menu?.setAttribute('aria-expanded','false')}));
document.getElementById('year').textContent=new Date().getFullYear();

const translations={
en:{services:'Services',standard:'The standard',contact:'Contact',book:'Book a visit',eyebrow:'AUTOMOTIVE DETAILING',location:'SHUWAIKH INDUSTRIAL / KUWAIT',since:'SINCE 2018',hero:'WHERE<br><em>DETAILS</em><br>MATTER.',heroSub:'Precision care for vehicles that deserve more than a quick clean.',standardLabel:'01 / THE STANDARD',standardTitle:'Clean is expected.<br><em>Exceptional is detailed.</em>',standardCopy:'Detailer is built around precision, presentation and the small things that change the way a vehicle looks and feels.',servicesLabel:'02 / SERVICES',servicesNote:'A focused approach to protection, finish and presentation.',s1:'PPF &<br>Protection',s1p:'Protection and finishing focused on preserving the vehicle’s surface and appearance.',s2:'Window<br>Tint',s2p:'Professional tinting for a cleaner look, added privacy and a refined finish.',s3:'Paint &<br>Detailing',s3p:'Careful polishing, detailing and finishing work for a cleaner, sharper presentation.',statement:'Precision<br>you can <em>see.</em>',experienceLabel:'03 / THE EXPERIENCE',experience:'More than<br><em>clean.</em>',experienceP:'A clean, considered environment where the vehicle remains the focus. Precise work, clear inspection and a professional setting come together to make the process feel as premium as the result.',finishLabel:'04 / THE FINISH',finishText:'EVERY<br>REFLECTION<br>COUNTS.',finishTag:'DETAILER / KUWAIT',visitLabel:'05 / VISIT DETAILER',visit:'Bring your<br><em>vehicle.</em>',visitP:'Professional detailing in Shuwaikh Industrial, Kuwait. Book directly through WhatsApp or contact the team for service information and availability.',directions:'Get directions',inst:'INSTAGRAM',wa:'WHATSAPP',call:'CALL DETAILER',precision:'Precision',presentation:'Presentation',care:'Care'},
ar:{services:'الخدمات',standard:'المعايير',contact:'تواصل معنا',book:'احجز موعداً',eyebrow:'العناية الاحترافية بالسيارات',location:'الشويخ الصناعية / الكويت',since:'منذ 2018',hero:'حيث<br><em>التفاصيل</em><br>تصنع الفرق.',heroSub:'عناية دقيقة لسيارات تستحق أكثر من مجرد تنظيف سريع.',standardLabel:'01 / المعايير',standardTitle:'النظافة متوقعة.<br><em>والتميّز في التفاصيل.</em>',standardCopy:'يعتمد ديتيلر على الدقة، وحسن المظهر، والتفاصيل الصغيرة التي تغيّر شكل السيارة وإحساسها.',servicesLabel:'02 / الخدمات',servicesNote:'نهج دقيق للحماية والمظهر واللمسة النهائية.',s1:'حماية<br>الطلاء PPF',s1p:'حماية وتشطيب احترافيان للمحافظة على سطح السيارة ومظهرها.',s2:'تظليل<br>النوافذ',s2p:'تظليل احترافي يمنح السيارة مظهراً أنظف وخصوصية ولمسة نهائية أنيقة.',s3:'طلاء<br>وتفصيل',s3p:'تلميع وعناية وتشطيب دقيق لمظهر أنظف وأكثر أناقة للسيارة.',statement:'دقة<br>يمكنك <em>رؤيتها.</em>',experienceLabel:'03 / التجربة',experience:'أكثر من<br><em>مجرد تنظيف.</em>',experienceP:'بيئة نظيفة ومدروسة يبقى فيها التركيز على السيارة. عمل دقيق وفحص واضح ومكان احترافي يجعل التجربة بمستوى النتيجة.',finishLabel:'04 / اللمسة النهائية',finishText:'كل<br>انعكاس<br>يهم.',finishTag:'ديتيلر / الكويت',visitLabel:'05 / زوروا ديتيلر',visit:'أحضر<br><em>سيارتك.</em>',visitP:'عناية احترافية بالسيارات في الشويخ الصناعية، الكويت. احجز مباشرة عبر واتساب أو تواصل معنا لمعرفة الخدمات والمواعيد.',directions:'احصل على الاتجاهات',inst:'إنستغرام',wa:'واتساب',call:'اتصل بديتيلر',precision:'الدقة',presentation:'المظهر',care:'العناية'}};

function set(sel,val){const e=document.querySelector(sel);if(e)e.innerHTML=val}
function applyLanguage(lang){const t=translations[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
set('.desktop-nav a:nth-child(1)',t.services);set('.desktop-nav a:nth-child(2)',t.standard);set('.desktop-nav a:nth-child(3)',t.contact);set('.header-book',t.book+' <span>↗</span>');set('.eyebrow',t.eyebrow);set('.location',t.location);set('.hero-index span',t.since);set('.hero h1',t.hero);set('.hero-bottom p',t.heroSub);
const labels=document.querySelectorAll('.section-label');if(labels[0])labels[0].innerHTML=t.standardLabel;if(labels[1])labels[1].innerHTML=t.servicesLabel;if(labels[2])labels[2].innerHTML=t.experienceLabel;if(labels[3])labels[3].innerHTML=t.finishLabel;if(labels[4])labels[4].innerHTML=t.visitLabel;
set('.standard h2',t.standardTitle);set('.standard-copy p',t.standardCopy);set('.section-head p',t.servicesNote);set('.card-one h3',t.s1);set('.card-one p',t.s1p);set('.card-two h3',t.s2);set('.card-two p',t.s2p);set('.card-three h3',t.s3);set('.card-three p',t.s3p);set('.black-statement h2',t.statement);set('.experience h2',t.experience);set('.large-copy',t.experienceP);set('.visual-left strong',t.finishText);set('.visual-right>span',t.finishTag);set('.contact-intro h2',t.visit);set('.contact-intro>p',t.visitP);set('.directions',t.directions+' <span>↗</span>');set('.contact-card a:nth-child(1) small',t.inst);set('.contact-card a:nth-child(2) small',t.wa);set('.contact-card a:nth-child(3) small',t.call);document.querySelector('.lang-toggle').textContent=lang==='en'?'العربية':'English';localStorage.setItem('detailer-language',lang)}
applyLanguage(localStorage.getItem('detailer-language')||'en');document.querySelector('.lang-toggle')?.addEventListener('click',()=>applyLanguage(document.documentElement.lang==='en'?'ar':'en'));

const targets=document.querySelectorAll('.service-card,.standard-main,.experience-grid,.visual-left,.visual-right,.contact-grid');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});targets.forEach(e=>{e.classList.add('reveal');io.observe(e)});